apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: abhinav-istio-mesh
  region: ap-south-1
  version: "1.33"

vpc:
  id: vpc-03a2794d55e651007
  subnets:
    public:
      ap-south-1a:
        id: subnet-0de464b9374299f4f
      ap-south-1b:
        id: subnet-0d19c48e203f9d89f
    private:
      ap-south-1a:
        id: subnet-0a84ff1d27a0ec841
      ap-south-1b:
        id: subnet-0d3c0e54898968775

iam:
  withOIDC: true
